- name: Disable Bluetooth (for using /dev/ttyAMA0)
  lineinfile:
    dest: '/boot/firmware/config.txt'
    insertafter: 'EOF'
    line: 'dtoverlay=disable-bt'

- name: Edit Fluentd Setting
  become: no
  replace: >-
    dest='~/rasp-python/etc/fluent.conf.aqua'
    regexp='{{ item.regexp }}'
    replace='{{ item.replace }}'
  with_items:
    - regexp: 'host\s+".*$'
      replace: 'host "{{ fluentd.aggr_host }}"'

- name: Setting Fluetd Autorun
  replace: >-
    dest='/etc/rc.local'
    regexp='fluentd .*'
    replace='fluentd -d /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.pid -c /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.conf.aqua -o /dev/shm/fluentd.log'

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
