- name: restart sshd
  service: name=ssh state=restarted

- name: restart timesyncd
  systemd: name=systemd-timesyncd.service state=restarted

- name: restart postfix 1
  systemd: name=ssh state=restarted
  listen: restart postfix

- name: restart postfix 2
  shell: newaliases
  listen: restart postfix

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
