- name: Install Packages
  apt:
    update-cache: 'yes'
    pkg:
      - bluetooth
      - python3-pip
      - libbluetooth-dev

- name: Install Python Bluez
  pip:
    # NOTE: '22/6 時点だと apt の python3-bluez だと「PY_SSIZE_T_CLEAN macro must be defined for '#' formats」が出る
    name: git+https://github.com/pybluez/pybluez

- name: Setting USB on
  blockinfile:
    dest: '/etc/rc.local'
    content: |
      # USB on
    insertbefore: 'exit 0'

- name: Setting Fluetd Autorun
  lineinfile:
    dest: '/etc/rc.local'
    insertbefore: 'exit 0'
    regex: '^fluentd.*$'
    line: 'fluentd -d /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.pid -c /home/{{ ansible_env["SUDO_USER"] }}/rasp-python/etc/fluent.conf.fplug -o /dev/shm/fluentd.log'
    
# Local Variables:
# mode: yaml
# tab-width: 4
# End:
