- name: Change Apt Repository
  replace:
    path: '/etc/apt/sources.list'
    regexp: 'http://ports\.ubuntu\.com'
    replace: 'http://jp.ports.ubuntu.com'

- name: Upgrade Packages
  apt:
    update_cache: 'yes'
    upgrade: 'yes'

- name: Install Packages
  apt:
    pkg:
      - postfix
      - i2c-tools
      - wiringpi
      - python-is-python3
      - python3-gpiozero
      - zsh
      - emacs-nox
      - git
      - mailutils
      - lsb-release
      - net-tools
      - daemontools
      - inetutils-traceroute
      - zabbix-agent
    update_cache: 'yes'
    cache_valid_time: 86400

- name: Setting Hostname
  lineinfile:
    dest: '/etc/hosts'
    regexp: '^127.0.1.1.*$'
    line: '127.0.1.1        {{ ansible_hostname }}'

- name: Setting Timezone
  timezone:
    name: 'Asia/Tokyo'

- name: Generate Locales
  locale_gen:
    name: '{{ item }}'
  with_items:
    - en_US.UTF-8
    - ja_JP.UTF-8

- name: Setting Sudo
  template:
    src: 'sudo/sudoers.j2'
    dest: '/etc/sudoers'
    owner: 'root'
    group: 'root'
    mode: '0440'

- name: Setting SSHD
  template:
    src: 'ssh/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
  notify: restart sshd

- name: Setting NTP client
  replace:
    path: '/etc/systemd/timesyncd.conf'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - regexp: '^#?NTP=.*$'
      replace: 'NTP={{ network.ntp }}'
    - regexp: '^#?FallbackNTP=.*$'
      replace: 'FallbackNTPNTP=ntp.nict.jp'
  notify: restart timesyncd

- name: Enable systemd-time-wait-sync
  systemd:
    name: systemd-time-wait-sync.service
    enabled: yes

- name: Create /etc/rc.local
  # NOTE: Wifi の場合は「ホスト名-wifi」でアクセスできるようにする
  lineinfile:
    dest: '/etc/rc.local'
    create: true
    owner: 'root'
    group: 'root'
    mode: '755'
    line: '#!/bin/bash'
    regexp: '#!/.*'
    insertbefore: 'BOF'

- name: Wait execution of rc.local until time synced
  lineinfile:
    dest: '/lib/systemd/system/rc-local.service'
    regexp: '^After=.*$'
    line: 'After=systemd-time-wait-sync.service'

- name: Setting USB off
  blockinfile:
    dest: '/etc/rc.local'
    content: |
      # USB off
      for i in 20980000.usb 3f980000.usb; do
        path="/sys/devices/platform/soc/${i}/buspower";
        if [ -e $path ]; then
          echo 0 > $path;
        fi;
      done
    insertbefore: 'exit 0'

- name: Setting Wifi - dhcp
  # NOTE: Wifi の場合は「ホスト名-wifi」でアクセスできるようにする
  lineinfile:
    dest: '/etc/dhcp/dhclient.conf'
    line: 'interface "wlan0" { send host-name = concat (gethostname(), "-wifi"); }'

- name: Setting Zabbix agent
  lineinfile:
    dest: '/etc/zabbix/zabbix_agentd.conf'
    regexp: '{{item.regexp}}'
    line: '{{item.line}}'
  with_items:
    - regexp: '^Server=.*$'
      line: 'Server={{network.zabbix}}'
    - regexp: '^ServerActive=.*$'
      line: 'ServerActive={{network.zabbix}}'
  notify: restart zabbix agent

- name: Enable I2C at 50kHz
  lineinfile:
    dest: '/boot/firmware/syscfg.txt'
    insertafter: 'dtparam=i2c_arm=on'
    line: 'dtparam=i2c_baudrate=50000'

- name: Load I2C module
  lineinfile:
    dest: '/etc/modules'
    line: 'i2c-dev'

- name: Setting Port drive strength
  lineinfile:
    dest: '/etc/rc.local'
    regexp: '^gpio drive.*$'
    line: 'gpio drive 0 7'
    insertbefore: 'exit 0'

- name: Setting WiFi - watch
  template:
    src: 'wifi/watch_wifi.zsh.j2'
    dest: '/usr/local/bin/watch_wifi.zsh'
    owner: 'root'
    group: 'root'
    mode: '755'

- name: Setting WiFi - watch cron
  cron:
    name: 'watch wifi connection'
    minute: '*/2'
    job: '/usr/local/bin/watch_wifi.zsh > /dev/null'


- name: Setting Postfix
  lineinfile:
    dest={{item.dest}}
    regexp={{item.regexp}}
    line={{item.line}}
  with_items:
    - dest: '/etc/postfix/main.cf'
      regexp: '^relayhost =.*'
      line: 'relayhost = [{{network.mail}}]'
    - dest: '/etc/postfix/main.cf'
      regexp: '^myhostname =.*'
      line: 'myhostname = {{ ansible_hostname }}'
    - dest: '/etc/aliases'
      regexp: '^root:.*'
      line: "root: {{network.root_mail}}"
  notify: restart postfix

- name: Boot nofitication
  lineinfile:
    dest: '/etc/rc.local'
    line: 'echo "System restarted at " `date` | mail -s "`hostname`: restart" root'
    insertbefore: 'exit 0'

- name: Enable Watchdog
  lineinfile:
    dest: '/boot/firmware/usercfg.txt'
    line: 'dtparam=watchdog=on'

- name: Setting Watchdog
  lineinfile:
    create: 'yes'
    dest: '/etc/modprobe.d/bcm2835-wdt.conf'
    regexp: '^options bcm2835_wdt heartbeat='
    line: 'options bcm2835_wdt heartbeat=30'

- name: Setting Heartbeat
  lineinfile:
    dest: '/etc/systemd/system.conf'
    regexp: '^#?RuntimeWatchdogSec'
    line: 'RuntimeWatchdogSec=10'

- name: Join I2C group
  user:
    name: ubuntu
    group: i2c
    append: yes

# Local Variables:
# mode: yaml
# tab-width: 4
# End:
